version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  
jobs:
  test:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: Npm Test
          command: |
            npm test

  login-aws:
    docker:
      - image: cimg/base:stable
    steps:
      - aws-ecr/ecr-login  

workflows:
  test-build-deploy:
    jobs:
      - test
      - login-aws:
          requires:
          - test
      - aws-ecr/build-and-push-image:
          repo: jseguros
          requires:
            - login-aws