version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  
jobs:
  test:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: Npm Test
          command: |
            npm test

workflows:
  test:
    jobs:
      - test
  deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: jseguros