version: 2.1
jobs:
  test:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: Npm Test
          command: |
            npm test

workflows:
  test:
    jobs:
      - test