version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  aws-ecs: circleci/aws-ecs@2.2.1
  
jobs:
  test:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: Npm Test
          command: |
            npm test

workflows:
  test-build-deploy:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          repo: "{AWS_ECR_REPOSITORY_IMAGE}"
          tag: '1.0.<< pipeline.number >>'
          requires:
            - test
      - aws-ecs/deploy-service-update:
          deployment-controller: ECS 
          container-image-name-updates: "container=node-juntoseguros,image-and-tag={AWS_ECR_ACCOUNT_URL}/{AWS_ECR_REPOSITORY_IMAGE}:1.0.<< pipeline.number >>"
          cluster-name: ECSJSeguros  
          family: junto-task-defination 
          force-new-deployment: true 
          max-poll-attempts: 1 
          service-name: service-juntoseguros
          requires:
            - aws-ecr/build-and-push-image